### PR TITLE
Added more documentation on color blindness

### PR DESCRIPTION
**Pull request by harshyadavcs**
For Issue #31

### CODE REVIEW

**Comment by harshyadavcs** [comment]
@elitadanilyuk Can I get your review on this please?

**Comment by harshyadavcs** [comment]
@elitadanilyuk

**Review by elitadanilyuk — APPROVED** [review]
Good addition!

**Comment by elitadanilyuk** [comment]
@harshyadavcs sorry for the slow review, I've been out of town. If you like the repo please feel free to star it!

**Comment by harshyadavcs** [comment]
> @harshyadavcs sorry for the slow review, I've been out of town. If you like the repo please feel free to star it!

Thank you for your review. I initially thought you didn't like my addition that's why no response. Will definitely star the repo.

**Pull request merged**
